#!/usr/bin/env python3
"""
preview.py — rebuild the isolated preview from source, idempotently.

The preview lives in /tmp/yuma-live and is served by /tmp/yuma-serve.py (a static server on
port 4173). Other projects sharing /tmp periodically wipe both. This script restores
everything in one safe-to-re-run command:

    python3 tools/preview.py                # sync, point preview at the public mirror sheet
    python3 tools/preview.py --sheet <id>   # use a different sheet for the preview

It:
  1. (re)writes /tmp/yuma-serve.py from the known-good template embedded below
  2. (re)creates /tmp/yuma-live and copies the runtime files + fonts/ media/ c/ vendor/
  3. prints the URL to open — with ?sheet=<public mirror> so the SOURCE app.js is never edited

Then start/refresh the existing preview server on port 4173. No sheet-id replacement, ever (that footgun is
gone: app.js reads ?sheet= as an override — see effectiveSheetId()).
"""
import os, sys, shutil

SRC   = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIVE  = "/tmp/yuma-live"
SERVE = "/tmp/yuma-serve.py"
# public, read-only MIRROR sheet for previewing without touching the private working copy
PREVIEW_SHEET = "10n4TFnuMWekZLD3pucKS050h1cNItcYmL9v0ciuBsSY"

SERVE_TEMPLATE = r'''#!/usr/bin/env python3
# Isolated static server for the Misfits Database preview (auto-generated by tools/preview.py).
# Serves ONLY our files from /tmp/yuma-live, sends no-store (kills stale-asset caching),
# and routes any foreign path back to index.html so neighbour demos can't leak in.
import http.server, socketserver, os
DIR = "/tmp/yuma-live"
ALLOW = {"/", "/index.html", "/app.js", "/styles.css", "/favicon.ico", "/favicon.svg", "/og-card.png", "/crt-screen-integration.js"}
PREFIX = ("/fonts/", "/media/", "/c/", "/vendor/")
class H(http.server.SimpleHTTPRequestHandler):
    def translate_path(self, path):
        clean = path.split("?", 1)[0].split("#", 1)[0]
        if clean in ALLOW or clean.startswith(PREFIX):
            return os.path.join(DIR, clean.lstrip("/")) or os.path.join(DIR, "index.html")
        return os.path.join(DIR, "index.html")           # foreign path → our app
    def end_headers(self):
        self.send_header("Cache-Control", "no-store, must-revalidate")
        super().end_headers()
    def log_message(self, *a): pass
os.chdir(DIR)
with socketserver.TCPServer(("", 4173), H) as httpd:
    httpd.serve_forever()
'''

def main():
    sheet = PREVIEW_SHEET
    if "--sheet" in sys.argv:
        sheet = sys.argv[sys.argv.index("--sheet") + 1]

    # 1. server script (always refresh to known-good)
    with open(SERVE, "w") as f:
        f.write(SERVE_TEMPLATE)
    print(f"✓ wrote {SERVE}")

    # 2. live dir + assets
    os.makedirs(LIVE, exist_ok=True)
    for fn in ["index.html", "styles.css", "app.js", "favicon.svg", "og-card.png", "crt-screen-integration.js"]:
        s = os.path.join(SRC, fn)
        if os.path.exists(s):
            shutil.copy2(s, os.path.join(LIVE, fn))
    # inject the preview's sheet override into the SERVED index.html (source untouched) so the
    # preview reads the public mirror at ANY url — no need to remember ?sheet=.
    live_index = os.path.join(LIVE, "index.html")
    if os.path.exists(live_index):
        with open(live_index, encoding="utf-8") as f:
            doc = f.read()
        inject = (f'<script>window.MDB_SHEET_OVERRIDE="{sheet}";'
                  f'/* preview-only override injected by tools/preview.py — source is untouched */</script>')
        if "MDB_SHEET_OVERRIDE" not in doc:
            doc = doc.replace("</head>", "  " + inject + "\n</head>", 1)
            with open(live_index, "w", encoding="utf-8") as f:
                f.write(doc)
    for d in ["fonts", "media", "c", "vendor"]:
        s = os.path.join(SRC, d)
        if os.path.isdir(s):
            shutil.copytree(s, os.path.join(LIVE, d), dirs_exist_ok=True)
    print(f"✓ synced app + fonts/ media/ c/ vendor/ into {LIVE}")

    print(f"✓ injected preview sheet override ({sheet[:8]}…) into served index.html (source untouched)")
    print("\nNext:")
    print("  • (re)start the preview server named 'yuma-roster' (port 4173).")
    print("  • open:  /  (the preview reads the public mirror automatically — no ?sheet= needed)")
    print(f"  • to force a different sheet for one load, append ?sheet=<id>")

if __name__ == "__main__":
    main()
